### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by sukiejosh** [dannyYassine/vuuri#2]

**Comment by madebyfabian** [comment]
Hey there,
thanks for writing this muuri vue wrapper! Wanted to use it in my vue3 project, and stumbled on a few problems. Maybe this will help to create a PR with the required changes:

- In `src/index.js`, there is this line: https://github.com/dannyYassine/vuuri/blob/996035390cd4b746d2cb2579cecf05d8caddd982/src/index.js#L1 which will not work, since vite is not allowing .vue files to import without extension -> easy to solve, just add '.vue'.

- Then, when I want to use the component, it errors 
`SyntaxError: The requested module '/node_modules/lodash/lodash.js?v=ac9922ab' does not provide an export named 'debounce'`. Seems like lodash isn't exporting anything. Can't solve this bug right now

- Since in vue3, the v-model's default prop name is not `value`, but `modelValue`, this has to be changed. Also the event 'input' is now `update:modelValue` -> easy to solve.

That's not all, but maybe it helps. Unfortunately I don't have time to create a PR with all required changes at the moment.

**Comment by electroheadfx** [comment]
Hello, any update of this great library for Vue 3 ?

**Comment by valentinwinkelmann** [comment]
Would be great if there was an update, VUE3 support would be awesome!

**Comment by dannyYassine** [comment]
Thanks for feedback!

I've started porting the library to vue3 with the composition syntax here: https://github.com/dannyYassine/vuuri/tree/next-vue3

Ill keep this thread up-to-date. Thanks!

**Comment by dannyYassine** [comment]
Hi all, 

vuuri is now compatible with vue-3 on version `0.4.0` on npm.

Thanks for your patience and help!

**Comment by madebyfabian** [comment]
@dannyYassine Thank you for your work! 😊
